#ifndef PORTABLE_WORDSIZES
#ifdef __MW_TARGET_USE_HARDWARE_RESOURCES_H__
#ifndef __MW_TARGET_HARDWARE_RESOURCES_H__
#define __MW_TARGET_HARDWARE_RESOURCES_H__

#define MW_MULTI_TASKING_MODE 1
#include "C:/ProgramData/MATLAB/SupportPackages/R2021a/toolbox/target/supportpackages/vexv5/include/MW_SupportFunc_Wrapper.h"
#include "MW_Vex_TaskControl.h"

#define MW_USECODERTARGET 1
#define MW_TARGETHARDWARE VEX V5 Robot Brain
#define MW_RTOS FreeRTOS
#define MW_RTOSBASERATETASKPRIORITY 14
#define MW_SCHEDULER_INTERRUPT_SOURCE 0
#define MW_RUNTIME_BUILDACTION 0
#define MW_DATAVERSION 2016.02
#define MW_CONNECTIONINFO_SERIAL_BAUDRATE 115200
#define MW_CONNECTIONINFO_SERIAL_COMPORT codertarget.vexv5.internal.getComPort()
#define MW_CONNECTIONINFO_SERIAL_VERBOSE 1
#define MW_EXTMODE_CONFIGURATION serial
#define MW_EXTMODE_SIGNALBUFFERSIZE 1000000.000000
#define MW_HOSTCOMPORT_SET_HOST_COM_PORT 0
#define MW_HOSTCOMPORT_COM_PORT_NUMBER 1
#define MW_DETECTTASKOVERRUNS 0.000000

#endif /* __MW_TARGET_HARDWARE_RESOURCES_H__ */

#endif

#endif
